
name: Hexo Auto-Deploy
on: [push]

jobs:
  build:
    name: Hexo Auto-Deploy by GitHub Actions
    runs-on: ubuntu-latest

    steps:
    - name: 1. git checkout...
      uses: actions/checkout@v1
      
    - name: 2. setup nodejs...
      uses: actions/setup-node@v1
      with:
          node-version: '17.4.x'
    
    - name: 3. install hexo...
      run: |
        npm i hexo-theme-butterfly
        npm install hexo-cli@4.2.0 -g
        npm install
        
    - name: 4. hexo generate public files...
      run: |
        hexo clean
        hexo generate

    - name: 5. hexo deploy ...
      run: |
        hexo deploy
